### ISSUE TITLE
CVES.json File Empty

### ISSUE THREAD

**Issue by ossie-git** [kitabisa/teler-resources#2]
For some reason, the cves.json file which was almost 5000 lines long a few months ago is now empty (this was due to a commit back in January). Is this intentional? If so, is there are a specific reason or have the rules been moved to another location? Thanks

**Comment by dwisiswant0** [comment]
Thanks for opening this issue, @ossie-git! We didn't realize that, now we're refactoring it.

**Comment by dwisiswant0** [comment]
Hi @ossie-git, database CVEs has been restored as per 7d5ed1a. Now, you have to clear resource caches with `teler --rm-cache` and run teler again, which it should work properly.

Again, thanks for your report!
